//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
            set {
                this["IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5074")]
        public int Port {
            get {
                return ((int)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ImageSize {
            get {
                return ((global::System.Drawing.Size)(this["ImageSize"]));
            }
            set {
                this["ImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LeftUpPoint {
            get {
                return ((global::System.Drawing.Point)(this["LeftUpPoint"]));
            }
            set {
                this["LeftUpPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RigntDownPoint {
            get {
                return ((global::System.Drawing.Point)(this["RigntDownPoint"]));
            }
            set {
                this["RigntDownPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TouchPadClickZ {
            get {
                return ((int)(this["TouchPadClickZ"]));
            }
            set {
                this["TouchPadClickZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"commandType\":15,\"param\":[{\"actionType\":1,\"x\":1440,\"y\":1056},{\"actionType\":3},{\"" +
            "actionType\":1,\"x\":1440,\"y\":1051},{\"actionType\":1,\"x\":1440,\"y\":1046},{\"actionType" +
            "\":1,\"x\":1445,\"y\":1040},{\"actionType\":1,\"x\":1445,\"y\":1035},{\"actionType\":1,\"x\":14" +
            "45,\"y\":1030},{\"actionType\":1,\"x\":1445,\"y\":1019},{\"actionType\":1,\"x\":1445,\"y\":100" +
            "3},{\"actionType\":1,\"x\":1445,\"y\":998},{\"actionType\":1,\"x\":1445,\"y\":992},{\"actionT" +
            "ype\":1,\"x\":1445,\"y\":987},{\"actionType\":1,\"x\":1445,\"y\":982},{\"actionType\":1,\"x\":1" +
            "445,\"y\":976},{\"actionType\":1,\"x\":1445,\"y\":971},{\"actionType\":1,\"x\":1445,\"y\":966}" +
            ",{\"actionType\":1,\"x\":1445,\"y\":950},{\"actionType\":1,\"x\":1445,\"y\":944},{\"actionTyp" +
            "e\":1,\"x\":1445,\"y\":939},{\"actionType\":1,\"x\":1445,\"y\":923},{\"actionType\":1,\"x\":144" +
            "5,\"y\":918},{\"actionType\":1,\"x\":1445,\"y\":912},{\"actionType\":1,\"x\":1445,\"y\":902},{" +
            "\"actionType\":1,\"x\":1445,\"y\":896},{\"actionType\":1,\"x\":1445,\"y\":891},{\"actionType\"" +
            ":1,\"x\":1445,\"y\":886},{\"actionType\":1,\"x\":1445,\"y\":875},{\"actionType\":1,\"x\":1445," +
            "\"y\":870},{\"actionType\":1,\"x\":1445,\"y\":864},{\"actionType\":1,\"x\":1445,\"y\":854},{\"a" +
            "ctionType\":1,\"x\":1445,\"y\":848},{\"actionType\":1,\"x\":1445,\"y\":843},{\"actionType\":1" +
            ",\"x\":1450,\"y\":838},{\"actionType\":1,\"x\":1450,\"y\":832},{\"actionType\":1,\"x\":1450,\"y" +
            "\":827},{\"actionType\":1,\"x\":1450,\"y\":816},{\"actionType\":1,\"x\":1450,\"y\":806},{\"act" +
            "ionType\":1,\"x\":1456,\"y\":800},{\"actionType\":1,\"x\":1456,\"y\":795},{\"actionType\":1,\"" +
            "x\":1456,\"y\":790},{\"actionType\":1,\"x\":1456,\"y\":784},{\"actionType\":1,\"x\":1456,\"y\":" +
            "779},{\"actionType\":1,\"x\":1456,\"y\":774},{\"actionType\":1,\"x\":1456,\"y\":768},{\"actio" +
            "nType\":1,\"x\":1456,\"y\":763},{\"actionType\":1,\"x\":1456,\"y\":758},{\"actionType\":1,\"x\"" +
            ":1456,\"y\":752},{\"actionType\":1,\"x\":1456,\"y\":747},{\"actionType\":1,\"x\":1456,\"y\":74" +
            "2},{\"actionType\":1,\"x\":1456,\"y\":731},{\"actionType\":1,\"x\":1456,\"y\":726},{\"actionT" +
            "ype\":1,\"x\":1456,\"y\":715},{\"actionType\":1,\"x\":1456,\"y\":710},{\"actionType\":1,\"x\":1" +
            "456,\"y\":704},{\"actionType\":1,\"x\":1456,\"y\":699},{\"actionType\":1,\"x\":1466,\"y\":704}" +
            ",{\"actionType\":1,\"x\":1472,\"y\":710},{\"actionType\":1,\"x\":1472,\"y\":715},{\"actionTyp" +
            "e\":1,\"x\":1477,\"y\":726},{\"actionType\":1,\"x\":1488,\"y\":731},{\"actionType\":1,\"x\":149" +
            "3,\"y\":742},{\"actionType\":1,\"x\":1493,\"y\":747},{\"actionType\":1,\"x\":1493,\"y\":752},{" +
            "\"actionType\":1,\"x\":1504,\"y\":758},{\"actionType\":1,\"x\":1520,\"y\":768},{\"actionType\"" +
            ":1,\"x\":1520,\"y\":774},{\"actionType\":1,\"x\":1520,\"y\":779},{\"actionType\":1,\"x\":1525," +
            "\"y\":784},{\"actionType\":1,\"x\":1530,\"y\":790},{\"actionType\":1,\"x\":1536,\"y\":795},{\"a" +
            "ctionType\":1,\"x\":1541,\"y\":806},{\"actionType\":1,\"x\":1546,\"y\":811},{\"actionType\":1" +
            ",\"x\":1552,\"y\":816},{\"actionType\":1,\"x\":1557,\"y\":822},{\"actionType\":1,\"x\":1562,\"y" +
            "\":827},{\"actionType\":1,\"x\":1568,\"y\":832},{\"actionType\":1,\"x\":1573,\"y\":838},{\"act" +
            "ionType\":1,\"x\":1584,\"y\":843},{\"actionType\":1,\"x\":1584,\"y\":848},{\"actionType\":1,\"" +
            "x\":1589,\"y\":854},{\"actionType\":1,\"x\":1600,\"y\":859},{\"actionType\":1,\"x\":1600,\"y\":" +
            "864},{\"actionType\":1,\"x\":1605,\"y\":870},{\"actionType\":1,\"x\":1616,\"y\":875},{\"actio" +
            "nType\":1,\"x\":1621,\"y\":880},{\"actionType\":1,\"x\":1621,\"y\":886},{\"actionType\":1,\"x\"" +
            ":1626,\"y\":891},{\"actionType\":1,\"x\":1626,\"y\":896},{\"actionType\":1,\"x\":1632,\"y\":90" +
            "2},{\"actionType\":1,\"x\":1648,\"y\":907},{\"actionType\":1,\"x\":1648,\"y\":912},{\"actionT" +
            "ype\":1,\"x\":1653,\"y\":923},{\"actionType\":1,\"x\":1653,\"y\":928},{\"actionType\":1,\"x\":1" +
            "669,\"y\":939},{\"actionType\":1,\"x\":1674,\"y\":944},{\"actionType\":1,\"x\":1674,\"y\":955}" +
            ",{\"actionType\":1,\"x\":1680,\"y\":960},{\"actionType\":1,\"x\":1685,\"y\":966},{\"actionTyp" +
            "e\":1,\"x\":1690,\"y\":976},{\"actionType\":1,\"x\":1701,\"y\":987},{\"actionType\":1,\"x\":171" +
            "2,\"y\":992},{\"actionType\":1,\"x\":1712,\"y\":1003},{\"actionType\":1,\"x\":1722,\"y\":1014}" +
            ",{\"actionType\":1,\"x\":1728,\"y\":1019},{\"actionType\":1,\"x\":1733,\"y\":1024},{\"actionT" +
            "ype\":1,\"x\":1749,\"y\":1035},{\"actionType\":1,\"x\":1749,\"y\":1040},{\"actionType\":1,\"x\"" +
            ":1760,\"y\":1051},{\"actionType\":1,\"x\":1770,\"y\":1062},{\"actionType\":1,\"x\":1776,\"y\":" +
            "1067},{\"actionType\":1,\"x\":1781,\"y\":1072},{\"actionType\":1,\"x\":1797,\"y\":1067},{\"ac" +
            "tionType\":1,\"x\":1797,\"y\":1062},{\"actionType\":1,\"x\":1802,\"y\":1056},{\"actionType\":" +
            "1,\"x\":1808,\"y\":1051},{\"actionType\":1,\"x\":1813,\"y\":1046},{\"actionType\":1,\"x\":1813" +
            ",\"y\":1040},{\"actionType\":1,\"x\":1824,\"y\":1035},{\"actionType\":1,\"x\":1829,\"y\":1030}" +
            ",{\"actionType\":1,\"x\":1834,\"y\":1024},{\"actionType\":1,\"x\":1834,\"y\":1019},{\"actionT" +
            "ype\":1,\"x\":1834,\"y\":1014},{\"actionType\":1,\"x\":1850,\"y\":1003},{\"actionType\":1,\"x\"" +
            ":1850,\"y\":998},{\"actionType\":1,\"x\":1861,\"y\":987},{\"actionType\":1,\"x\":1866,\"y\":98" +
            "2},{\"actionType\":1,\"x\":1872,\"y\":976},{\"actionType\":1,\"x\":1872,\"y\":971},{\"actionT" +
            "ype\":1,\"x\":1877,\"y\":966},{\"actionType\":1,\"x\":1877,\"y\":960},{\"actionType\":1,\"x\":1" +
            "877,\"y\":955},{\"actionType\":1,\"x\":1882,\"y\":950},{\"actionType\":1,\"x\":1882,\"y\":944}" +
            ",{\"actionType\":1,\"x\":1893,\"y\":939},{\"actionType\":1,\"x\":1898,\"y\":934},{\"actionTyp" +
            "e\":1,\"x\":1904,\"y\":928},{\"actionType\":1,\"x\":1904,\"y\":923},{\"actionType\":1,\"x\":190" +
            "9,\"y\":918},{\"actionType\":1,\"x\":1914,\"y\":912},{\"actionType\":1,\"x\":1925,\"y\":907},{" +
            "\"actionType\":1,\"x\":1925,\"y\":902},{\"actionType\":1,\"x\":1930,\"y\":896},{\"actionType\"" +
            ":1,\"x\":1941,\"y\":891},{\"actionType\":1,\"x\":1941,\"y\":886},{\"actionType\":1,\"x\":1952," +
            "\"y\":880},{\"actionType\":1,\"x\":1957,\"y\":875},{\"actionType\":1,\"x\":1968,\"y\":864},{\"a" +
            "ctionType\":1,\"x\":1973,\"y\":859},{\"actionType\":1,\"x\":1978,\"y\":854},{\"actionType\":1" +
            ",\"x\":1989,\"y\":848},{\"actionType\":1,\"x\":1989,\"y\":843},{\"actionType\":1,\"x\":1994,\"y" +
            "\":838},{\"actionType\":1,\"x\":2005,\"y\":832},{\"actionType\":1,\"x\":2016,\"y\":822},{\"act" +
            "ionType\":1,\"x\":2026,\"y\":816},{\"actionType\":1,\"x\":2032,\"y\":811},{\"actionType\":1,\"" +
            "x\":2042,\"y\":800},{\"actionType\":1,\"x\":2053,\"y\":795},{\"actionType\":1,\"x\":2058,\"y\":" +
            "790},{\"actionType\":1,\"x\":2064,\"y\":784},{\"actionType\":1,\"x\":2069,\"y\":779},{\"actio" +
            "nType\":1,\"x\":2080,\"y\":774},{\"actionType\":1,\"x\":2085,\"y\":768},{\"actionType\":1,\"x\"" +
            ":2085,\"y\":763},{\"actionType\":1,\"x\":2101,\"y\":758},{\"actionType\":1,\"x\":2106,\"y\":75" +
            "2},{\"actionType\":1,\"x\":2106,\"y\":747},{\"actionType\":1,\"x\":2106,\"y\":742},{\"actionT" +
            "ype\":1,\"x\":2117,\"y\":736},{\"actionType\":1,\"x\":2117,\"y\":731},{\"actionType\":1,\"x\":2" +
            "117,\"y\":726},{\"actionType\":1,\"x\":2117,\"y\":720},{\"actionType\":1,\"x\":2117,\"y\":715}" +
            ",{\"actionType\":1,\"x\":2122,\"y\":715},{\"actionType\":2}],\"messageId\":\"0edfddcd-f1d8-" +
            "4b40-b697-5f3a387959d5\"}")]
        public string dddd {
            get {
                return ((string)(this["dddd"]));
            }
            set {
                this["dddd"] = value;
            }
        }
    }
}
